{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /inventario/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.codigo_lote\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py\", line 22, in index\n    return render(request, 'inventario/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.codigo_lote", "status_code": 500, "request": "<WSGIRequest: GET '/inventario/'>"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /pedidos/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: pedidos_pedido.ruta_entrega_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/pedidos/views.py\", line 32, in index\n    return render(request, 'pedidos/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: pedidos_pedido.ruta_entrega_id", "status_code": 500, "request": "<WSGIRequest: GET '/pedidos/'>"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /pedidos/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: pedidos_pedido.ruta_entrega_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/pedidos/views.py\", line 32, in index\n    return render(request, 'pedidos/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: pedidos_pedido.ruta_entrega_id", "status_code": 500, "request": "<WSGIRequest: GET '/pedidos/'>"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/admin.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/admin.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/admin.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/dashboard/views.py\", line 41, in index\n    low_stock_products = Producto.objects.filter(stock__lte=low_stock_threshold).count()\n                         ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/query.py\", line 1476, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/query.py\", line 1494, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/query.py\", line 1501, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 1609, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 1641, in _add_q\n    child_clause, needed_inner = self.build_filter(\n                                 ~~~~~~~~~~~~~~~~~^\n        child,\n        ^^^^^^\n    ...<7 lines>...\n        update_join_types=update_join_types,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 1491, in build_filter\n    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)\n                                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 1303, in solve_lookup_type\n    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())\n                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 1768, in names_to_path\n    raise FieldError(\n    ...<2 lines>...\n    )\ndjango.core.exceptions.FieldError: Cannot resolve keyword 'stock' into field. Choices are: activo, cantidad_stock, categoria, categoria_id, codigo, codigo_lote, costo, descripcion, detallepedido, fecha_actualizacion, fecha_creacion, id, imagen, incidencia, nombre, precio, predicciondemanda, registrocalidad, unidad", "status_code": 500, "request": "<WSGIRequest: GET '/'>"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Not Found: /favicon.ico", "status_code": 404, "request": "<WSGIRequest: GET '/favicon.ico'>"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/dashboard/views.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.cantidad_stock\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/dashboard/views.py\", line 41, in index\n    low_stock_products = Producto.objects.filter(cantidad_stock__lte=low_stock_threshold).count()\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/query.py\", line 620, in count\n    return self.query.get_count(using=self.db)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 630, in get_count\n    return obj.get_aggregation(using, {\"__count\": Count(\"*\")})[\"__count\"]\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 616, in get_aggregation\n    result = compiler.execute_sql(SINGLE)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.cantidad_stock", "status_code": 500, "request": "<WSGIRequest: GET '/'>"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/api/views.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/pedidos/views.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.cantidad_stock\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/dashboard/views.py\", line 41, in index\n    low_stock_products = Producto.objects.filter(cantidad_stock__lte=low_stock_threshold).count()\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/query.py\", line 620, in count\n    return self.query.get_count(using=self.db)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 630, in get_count\n    return obj.get_aggregation(using, {\"__count\": Count(\"*\")})[\"__count\"]\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 616, in get_aggregation\n    result = compiler.execute_sql(SINGLE)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.cantidad_stock", "status_code": 500, "request": "<WSGIRequest: GET '/'>"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/informes/views.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/dashboard/views.py\", line 41, in index\n    low_stock_products = Producto.objects.filter(stock__lte=low_stock_threshold).count()\n                         ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1476, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1494, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1501, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 1609, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 1641, in _add_q\n    child_clause, needed_inner = self.build_filter(\n                                 ~~~~~~~~~~~~~~~~~^\n        child,\n        ^^^^^^\n    ...<7 lines>...\n        update_join_types=update_join_types,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 1491, in build_filter\n    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)\n                                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 1303, in solve_lookup_type\n    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())\n                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 1768, in names_to_path\n    raise FieldError(\n    ...<2 lines>...\n    )\ndjango.core.exceptions.FieldError: Cannot resolve keyword 'stock' into field. Choices are: activo, cantidad_stock, categoria, categoria_id, codigo, codigo_lote, costo, descripcion, detallepedido, fecha_actualizacion, fecha_creacion, id, imagen, incidencia, nombre, precio, predicciondemanda, registrocalidad, unidad", "status_code": 500, "request": "<WSGIRequest: GET '/'>"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Not Found: /favicon.ico", "status_code": 404, "request": "<WSGIRequest: GET '/favicon.ico'>"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/dashboard/views.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/api/views.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/pedidos/views.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.cantidad_stock\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/dashboard/views.py\", line 41, in index\n    low_stock_products = Producto.objects.filter(cantidad_stock__lte=low_stock_threshold).count()\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 620, in count\n    return self.query.get_count(using=self.db)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 630, in get_count\n    return obj.get_aggregation(using, {\"__count\": Count(\"*\")})[\"__count\"]\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 616, in get_aggregation\n    result = compiler.execute_sql(SINGLE)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.cantidad_stock", "status_code": 500, "request": "<WSGIRequest: GET '/'>"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.cantidad_stock\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/dashboard/views.py\", line 41, in index\n    low_stock_products = Producto.objects.filter(cantidad_stock__lte=low_stock_threshold).count()\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 620, in count\n    return self.query.get_count(using=self.db)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 630, in get_count\n    return obj.get_aggregation(using, {\"__count\": Count(\"*\")})[\"__count\"]\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 616, in get_aggregation\n    result = compiler.execute_sql(SINGLE)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.cantidad_stock", "status_code": 500, "request": "<WSGIRequest: GET '/'>"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.cantidad_stock\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/dashboard/views.py\", line 41, in index\n    low_stock_products = Producto.objects.filter(cantidad_stock__lte=low_stock_threshold).count()\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 620, in count\n    return self.query.get_count(using=self.db)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 630, in get_count\n    return obj.get_aggregation(using, {\"__count\": Count(\"*\")})[\"__count\"]\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/query.py\", line 616, in get_aggregation\n    result = compiler.execute_sql(SINGLE)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.cantidad_stock", "status_code": 500, "request": "<WSGIRequest: GET '/'>"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/dashboard/views.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/dashboard/views.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /inventario/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.codigo\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py\", line 22, in index\n    return render(request, 'inventario/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.codigo", "status_code": 500, "request": "<WSGIRequest: GET '/inventario/'>"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /pedidos/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: pedidos_pedido.ruta_entrega_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/pedidos/views.py\", line 32, in index\n    return render(request, 'pedidos/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: pedidos_pedido.ruta_entrega_id", "status_code": 500, "request": "<WSGIRequest: GET '/pedidos/'>"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /inventario/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.codigo\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py\", line 22, in index\n    return render(request, 'inventario/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.codigo", "status_code": 500, "request": "<WSGIRequest: GET '/inventario/'>"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /inventario/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.codigo\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py\", line 22, in index\n    return render(request, 'inventario/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.codigo", "status_code": 500, "request": "<WSGIRequest: GET '/inventario/'>"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /inventario/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.codigo\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py\", line 22, in index\n    return render(request, 'inventario/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.codigo", "status_code": 500, "request": "<WSGIRequest: GET '/inventario/'>"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /inventario/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.codigo\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py\", line 22, in index\n    return render(request, 'inventario/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.codigo", "status_code": 500, "request": "<WSGIRequest: GET '/inventario/'>"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/pedidos/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /inventario/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.codigo\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py\", line 22, in index\n    return render(request, 'inventario/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.codigo", "status_code": 500, "request": "<WSGIRequest: GET '/inventario/'>"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /pedidos/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: pedidos_pedido.ruta_entrega_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/pedidos/views.py\", line 32, in index\n    return render(request, 'pedidos/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: pedidos_pedido.ruta_entrega_id", "status_code": 500, "request": "<WSGIRequest: GET '/pedidos/'>"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /inventario/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.codigo\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py\", line 22, in index\n    return render(request, 'inventario/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.codigo", "status_code": 500, "request": "<WSGIRequest: GET '/inventario/'>"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/pedidos/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/pedidos/models.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /inventario/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.codigo\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py\", line 22, in index\n    return render(request, 'inventario/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.codigo", "status_code": 500, "request": "<WSGIRequest: GET '/inventario/'>"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /pedidos/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: pedidos_pedido.ruta_entrega_id\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/pedidos/views.py\", line 32, in index\n    return render(request, 'pedidos/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: pedidos_pedido.ruta_entrega_id", "status_code": 500, "request": "<WSGIRequest: GET '/pedidos/'>"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /inventario/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.codigo\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py\", line 22, in index\n    return render(request, 'inventario/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.codigo", "status_code": 500, "request": "<WSGIRequest: GET '/inventario/'>"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/migrations/0001_initial.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /inventario/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.codigo\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py\", line 22, in index\n    return render(request, 'inventario/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.codigo", "status_code": 500, "request": "<WSGIRequest: GET '/inventario/'>"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/migrations/0001_initial.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /inventario/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.codigo\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py\", line 22, in index\n    return render(request, 'inventario/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.codigo", "status_code": 500, "request": "<WSGIRequest: GET '/inventario/'>"}
{"timestamp": null, "level": null, "name": "django.request", "message": "Internal Server Error: /inventario/", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nsqlite3.OperationalError: no such column: inventario_producto.codigo\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/contrib/auth/decorators.py\", line 60, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n  File \"/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/views.py\", line 22, in index\n    return render(request, 'inventario/index.html', context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/shortcuts.py\", line 25, in render\n    content = loader.render_to_string(template_name, context, request, using=using)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader.py\", line 62, in render_to_string\n    return template.render(context, request)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/backends/django.py\", line 107, in render\n    return self.template.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 171, in render\n    return self._render(context)\n           ~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 159, in render\n    return compiled_parent._render(context)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 163, in _render\n    return self.nodelist.render(context)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/loader_tags.py\", line 65, in render\n    result = block.nodelist.render(context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 1008, in render\n    return SafeString(\"\".join([node.render_annotated(context) for node in self]))\n                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/base.py\", line 969, in render_annotated\n    return self.render(context)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/template/defaulttags.py\", line 199, in render\n    len_values = len(values)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 382, in __len__\n    self._fetch_all()\n    ~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 1928, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size\n    )\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/models/sql/compiler.py\", line 1574, in execute_sql\n    cursor.execute(sql, params)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 122, in execute\n    return super().execute(sql, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 79, in execute\n    return self._execute_with_wrappers(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        sql, params, many=False, executor=self._execute\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 92, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 100, in _execute\n    with self.db.wrap_database_errors:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/utils.py\", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py\", line 354, in execute\n    return super().execute(query, params)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\ndjango.db.utils.OperationalError: no such column: inventario_producto.codigo", "status_code": 500, "request": "<WSGIRequest: GET '/inventario/'>"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/migrations/0001_initial.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "/Users/renekuhm/Desktop/ecomerce/seafood_backend/inventario/migrations/0001_initial.py changed, reloading."}
{"timestamp": null, "level": null, "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader"}
